-- Migration 002: documents table + chunks FK + context_header + embedding_model_version
--
-- Adds provenance tracking at the document level (one raw document produces
-- N chunks). Enables re-chunking, deduplication via content hash, and
-- staleness tracking without touching the chunks table data.
--
-- Also extends the chunks table with two columns that support the
-- Anthropic Contextual Retrieval pattern and future embedding-model upgrades:
--   context_header        — prepended to content before embedding; stored so
--                           it can be inspected and regenerated without re-
--                           fetching the raw document.
--   embedding_model_version — which model produced this embedding vector;
--                           allows selective re-embedding when the model changes.
--
-- Prerequisites:
--   - Migration 001 applied (chunks table must exist).
--
-- Idempotent: safe to run on a project where 002 was already applied.

-- ---------------------------------------------------------------------------
-- documents table
-- ---------------------------------------------------------------------------

create table if not exists documents (
    id                  uuid        primary key default gen_random_uuid(),

    -- Where the document came from. Matches ChunkMetadata.url so a join
    -- is possible without extra metadata columns.
    url                 text        not null,

    -- SHA-256 hex digest of the raw content at fetch time. Used for
    -- deduplication: skip re-ingestion if content_hash has not changed.
    content_hash        text        not null,

    -- Raw text of the document as fetched (Markdown from FireCrawl, etc.).
    -- Kept so the chunker can be re-run without re-fetching.
    raw_content         text,

    -- Mirrors ChunkMetadata.source_type (press_release, blog_post, etc.)
    source_type         text        not null,

    -- Company this document belongs to (mirrors ChunkMetadata.company).
    company             text        not null,

    -- When the connector fetched the document. Distinct from chunk created_at.
    fetched_at          timestamptz not null default now(),

    -- Lifecycle: pending → chunked → embedded → done, or → error.
    ingestion_status    text        not null default 'pending'
                            check (ingestion_status in
                                ('pending', 'chunked', 'embedded', 'done', 'error')),

    -- Last error message if ingestion_status = 'error'.
    error_detail        text,

    -- ---------------------------------------------------------------------------
    -- Storage references (used when the document is a binary asset: PDF, image)
    -- ---------------------------------------------------------------------------

    -- Supabase Storage bucket name (e.g. 'raw-documents').
    storage_bucket      text,

    -- Path within the bucket (e.g. '2026/05/celonis-earnings-q1.pdf').
    storage_path        text,

    -- MIME type of the stored asset ('application/pdf', 'image/png', etc.).
    mime_type           text,

    -- ---------------------------------------------------------------------------
    -- Visual pipeline outputs (populated by Pipeline A / Pipeline B)
    -- ---------------------------------------------------------------------------

    -- Short caption generated by the vision LLM; prepended as context_header
    -- for image chunks (Pipeline A — embedding for retrieval).
    vision_caption      text,

    -- OCR text extracted from the document (PDFs, screenshots).
    ocr_text            text,

    -- Structured feature data produced by Pipeline B (visual brand analysis).
    -- Keys vary by visual type: logo analysis, layout scores, colour palette, etc.
    -- Stored as jsonb so capability agents can query specific fields.
    visual_features     jsonb       default '{}'
);

-- ---------------------------------------------------------------------------
-- Indexes on documents
-- ---------------------------------------------------------------------------

-- Fast lookup by URL (dedup check at ingest time).
create index if not exists documents_url_idx
    on documents (url);

-- Fast lookup by content hash (skip re-ingestion if unchanged).
create unique index if not exists documents_content_hash_uidx
    on documents (content_hash);

-- Filter by company + source_type (most common metadata pre-filter).
create index if not exists documents_company_source_type_idx
    on documents (company, source_type);

-- Filter by ingestion status (worker queue polls for 'pending' / 'error').
create index if not exists documents_ingestion_status_idx
    on documents (ingestion_status);

-- ---------------------------------------------------------------------------
-- Extend chunks table
-- ---------------------------------------------------------------------------

-- Foreign key back to the parent document. Nullable: chunks created before
-- this migration (or via direct insert without a document record) are allowed.
alter table chunks
    add column if not exists document_id uuid
        references documents (id) on delete set null;

-- The context header that was prepended to content before embedding.
-- Storing it here means the vector can be regenerated deterministically,
-- and the UI can show the header alongside the raw chunk for transparency.
alter table chunks
    add column if not exists context_header text;

-- Which embedding model produced the vector in the embedding column.
-- Default matches the model used in migration 001.
-- When the project upgrades to a new model, old chunks are identifiable
-- and can be re-embedded selectively without touching chunks that are
-- already up to date.
alter table chunks
    add column if not exists embedding_model_version text
        not null default 'text-embedding-3-small';

-- ---------------------------------------------------------------------------
-- Index on the new FK for reverse lookups (all chunks of a document).
-- ---------------------------------------------------------------------------

create index if not exists chunks_document_id_idx
    on chunks (document_id);
